apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poste.fullname" . }}-data-pvc
  labels:
    {{- include "poste.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
